import { useState, useRef, useCallback } from 'react'
import FindingsPanel from '../components/FindingsPanel'
import './PredictionPage.css'

const API = '/api'
const STATUS = { IDLE: 'idle', VALIDATING: 'validating', READY: 'ready', ANALYSING: 'analysing', DONE: 'done', ERROR: 'error' }

export default function PredictionPage() {
  const [status, setStatus]     = useState(STATUS.IDLE)
  const [errorMsg, setErrorMsg] = useState('')
  const [preview, setPreview]   = useState(null)
  const [file, setFile]         = useState(null)
  const [result, setResult]     = useState(null)
  const [xaiMode, setXaiMode]   = useState(false)
  const [dragging, setDragging] = useState(false)
  const inputRef    = useRef()
  const previewUrl  = useRef(null)

  const handleFile = useCallback(async (f) => {
    if (!f) return
    if (previewUrl.current) {
      URL.revokeObjectURL(previewUrl.current)
    }
    const objectUrl = URL.createObjectURL(f)
    previewUrl.current = objectUrl
    setResult(null); setErrorMsg(''); setXaiMode(false)
    setPreview(objectUrl)
    setFile(f)
    setStatus(STATUS.VALIDATING)

    const fd = new FormData()
    fd.append('file', f)
    try {
      const res  = await fetch(`${API}/validate`, { method: 'POST', body: fd })
      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        setStatus(STATUS.ERROR)
        setErrorMsg(data.detail || `Validation error (${res.status})`)
        return
      }
      const data = await res.json()
      if (!data.valid) { setStatus(STATUS.ERROR); setErrorMsg(data.reason) }
      else              { setStatus(STATUS.READY) }
    } catch {
      setStatus(STATUS.ERROR)
      setErrorMsg('Could not reach the backend. Make sure the server is running on port 8000.')
    }
  }, [])

  const onDrop      = useCallback((e) => { e.preventDefault(); setDragging(false); const f = e.dataTransfer.files[0]; if (f) handleFile(f) }, [handleFile])
  const onDragOver  = (e) => { e.preventDefault(); setDragging(true) }
  const onDragLeave = () => setDragging(false)
  const onInputChange = (e) => { if (e.target.files[0]) handleFile(e.target.files[0]) }

  const analyse = async () => {
    if (!file || status !== STATUS.READY) return
    setStatus(STATUS.ANALYSING); setResult(null)
    const fd = new FormData()
    fd.append('file', file)
    try {
      const res  = await fetch(`${API}/predict`, { method: 'POST', body: fd })
      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        setStatus(STATUS.ERROR)
        setErrorMsg(data.detail || `Server error (${res.status})`)
        return
      }
      const data = await res.json()
      setResult(data); setStatus(STATUS.DONE)
    } catch {
      setStatus(STATUS.ERROR)
      setErrorMsg('Analysis failed. Make sure the backend is running and models are loaded.')
    }
  }

  const reset = () => {
    if (previewUrl.current) {
      URL.revokeObjectURL(previewUrl.current)
      previewUrl.current = null
    }
    setStatus(STATUS.IDLE); setFile(null); setPreview(null)
    setResult(null); setErrorMsg(''); setXaiMode(false)
    if (inputRef.current) inputRef.current.value = ''
  }

  const downloadImage = (b64, name) => {
    const link = document.createElement('a')
    link.href = `data:image/jpeg;base64,${b64}`
    link.download = name; link.click()
  }

  const downloadReport = () => {
    if (!result) return
    const lines = [
      'iDentify — Dental Pathology Detection Report',
      '==============================================',
      `Date: ${new Date().toLocaleString()}`,
      `Total Detections: ${result.total_found}`,
      '',
      'Detections:',
      ...result.detections.map((d, i) =>
        `  ${i + 1}. ${d.label} — Confidence: ${d.confidence_pct} | Box: [${d.box.join(', ')}]`
      ),
      '',
      'DISCLAIMER: This report is generated by an AI system for research and educational use only.',
      'It does not constitute a clinical diagnosis. Always consult a qualified dental professional.',
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url; link.download = 'iDentify_report.txt'; link.click()
    URL.revokeObjectURL(url)
  }

  const isLoading  = status === STATUS.VALIDATING || status === STATUS.ANALYSING
  const displaySrc = result
    ? `data:image/jpeg;base64,${xaiMode ? result.image_xai : result.image_standard}`
    : preview

  return (
    <div className="prediction-page page">
      <div className="pred-layout">

        <div className="pred-left">

          {status === STATUS.IDLE && (
            <div
              className={`upload-zone ${dragging ? 'dragging' : ''}`}
              onDrop={onDrop} onDragOver={onDragOver} onDragLeave={onDragLeave}
              onClick={() => inputRef.current?.click()}
            >
              <input ref={inputRef} type="file" accept="image/*" style={{ display: 'none' }} onChange={onInputChange} />
              <div className="upload-icon">📡</div>
              <p className="upload-title">Drop your OPG here</p>
              <p className="upload-sub">or click to browse · JPG, PNG · min 400×200 px</p>
            </div>
          )}

          {status !== STATUS.IDLE && displaySrc && (
            <div className="image-viewer">
              <img src={displaySrc} alt="OPG" className="opg-img" />

              {isLoading && (
                <div className="img-overlay">
                  <div className="spinner" />
                  <span>{status === STATUS.VALIDATING ? 'Validating image…' : 'Analysing OPG…'}</span>
                </div>
              )}

              {status === STATUS.DONE && (
                <div className="img-toolbar">
                  <button className={`toggle-btn ${!xaiMode ? 'active' : ''}`} onClick={() => setXaiMode(false)}>Standard</button>
                  <button className={`toggle-btn ${xaiMode ? 'active' : ''}`}  onClick={() => setXaiMode(true)}>XAI Heatmap</button>
                </div>
              )}
            </div>
          )}

          {status === STATUS.ERROR && (
            <div className="error-box">
              <span className="error-icon">⚠</span>
              <p>{errorMsg}</p>
            </div>
          )}

          <div className="controls-row">
            {status === STATUS.READY && (
              <button className="btn btn-primary analyse-btn" onClick={analyse}>Analyse OPG</button>
            )}
            {status === STATUS.DONE && (
              <>
                <button className="btn btn-ghost" onClick={() => downloadImage(result.image_standard, 'iDentify_standard.jpg')}>⬇ Download</button>
                <button className="btn btn-ghost" onClick={() => downloadImage(result.image_xai,      'iDentify_xai.jpg')}>⬇ XAI Image</button>
                <button className="btn btn-ghost" onClick={downloadReport}>⬇ Report</button>
              </>
            )}
            {status !== STATUS.IDLE && (
              <button className="btn btn-ghost" onClick={reset}>✕ Reset</button>
            )}
            {status === STATUS.IDLE && (
              <p className="upload-hint">Upload a panoramic dental radiograph to begin.</p>
            )}
          </div>

        </div>

        <div className="pred-right">
          <FindingsPanel status={status} result={result} />
        </div>

      </div>
    </div>
  )
}