import { useState } from 'react';
import './App.css';

function App() {
  const [selectedFile, setSelectedFile] = useState(null);
  const [preview, setPreview] = useState(null);
  
  // We now store TWO result images
  const [resultStandard, setResultStandard] = useState(null);
  const [resultXAI, setResultXAI] = useState(null);
  
  const [loading, setLoading] = useState(false);
  const [detections, setDetections] = useState([]);
  
  // Toggle State
  const [showXAI, setShowXAI] = useState(false);

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    if (file) {
      setSelectedFile(file);
      setPreview(URL.createObjectURL(file));
      setResultStandard(null);
      setResultXAI(null);
      setDetections([]);
      setShowXAI(false);
    }
  };

  const handleUpload = async () => {
    if (!selectedFile) return;

    setLoading(true);
    const formData = new FormData();
    formData.append("file", selectedFile);

    try {
      const response = await fetch("http://localhost:8000/predict", {
        method: "POST",
        body: formData,
      });

      const data = await response.json();

      // Store both versions
      setResultStandard(`data:image/jpeg;base64,${data.image_standard}`);
      setResultXAI(`data:image/jpeg;base64,${data.image_xai}`);
      setDetections(data.detections);
      
    } catch (error) {
      console.error("Error:", error);
      alert("Error connecting to backend.");
    } finally {
      setLoading(false);
    }
  };

  // --- DOWNLOAD HELPERS ---
  const downloadImage = (dataUrl, filename) => {
    const link = document.createElement('a');
    link.href = dataUrl;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const downloadReport = () => {
    const date = new Date().toLocaleString();
    let content = `🦷 iDentify AI Diagnosis Report\n`;
    content += `Date: ${date}\n`;
    content += `File: ${selectedFile.name}\n`;
    content += `--------------------------------\n\n`;
    
    if (detections.length === 0) {
      content += "No pathologies detected (Healthy).\n";
    } else {
      detections.forEach((det, idx) => {
        content += `${idx + 1}. ${det.diagnosis.toUpperCase()}\n`;
        content += `   Confidence: ${(det.confidence * 100).toFixed(2)}%\n`;
        content += `   Location: [x:${det.box[0]}, y:${det.box[1]}]\n\n`;
      });
    }

    content += `--------------------------------\n`;
    content += `Generated by iDentify MVP\n`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Report_${selectedFile.name.split('.')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="container">
      <h1>🦷 iDentify: Dental AI Assistant</h1>
      
      <div className="upload-box">
        <input type="file" accept="image/*" onChange={handleFileChange} />
        <button onClick={handleUpload} disabled={!selectedFile || loading}>
          {loading ? "Analyzing..." : "Analyze X-Ray"}
        </button>
      </div>

      <div className="results-area">
        {/* IMAGE PANEL */}
        <div className="image-panel">
          {resultStandard ? (
            <div className="result-container">
              {/* The Image (Switches based on Toggle) */}
              <img 
                src={showXAI ? resultXAI : resultStandard} 
                alt="Result" 
                className="xray-img" 
              />
              
              {/* CONTROLS */}
              <div className="controls">
                <button 
                  className={`toggle-btn ${showXAI ? 'active' : ''}`}
                  onClick={() => setShowXAI(!showXAI)}
                >
                  {showXAI ? "Hide XAI Reasoning" : "Show XAI Reasoning"}
                </button>

                <div className="download-group">
                  <button onClick={() => downloadImage(resultStandard, `Analysis_${selectedFile.name}`)}>
                    ⬇ Img
                  </button>
                  <button onClick={() => downloadImage(resultXAI, `XAI_${selectedFile.name}`)}>
                    ⬇ XAI
                  </button>
                  <button onClick={downloadReport}>
                    📄 Report
                  </button>
                </div>
              </div>
            </div>
          ) : preview ? (
            <img src={preview} alt="Preview" className="xray-img preview" />
          ) : (
            <div className="placeholder">Upload an OPG X-Ray</div>
          )}
        </div>

        {/* REPORT PANEL */}
        {detections.length > 0 && (
          <div className="report-panel">
            <h3>📋 Findings</h3>
            <ul>
              {detections.map((det, index) => (
                <li key={index} className="issue">
                  <strong>{det.diagnosis.toUpperCase()}</strong>
                  <br />
                  <span className="conf">Conf: {(det.confidence * 100).toFixed(1)}%</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}

export default App;